harbro/Controllers/HomeController.cs
using Harbro.Web.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Harbro.Web.Controllers {

    [Authorize]
    public class HomeController : Controller{

        private CustomerContext customerContext;

        public HomeController(CustomerContext customerContext) {
            this.customerContext = customerContext;
            }

        public IActionResult Index(string message) {

            ViewBag.Message = message;
            return View();
        }
        public IActionResult Messages() {
            return View();
        }
        public IActionResult Help() {
            return View();
        }
        public IActionResult Settings() {
            return View();
        }
    }
}

harbro/Controllers/OrderController.cs
using AutoMapper;
using Harbro.Web.Controllers.Extensions;
using Harbro.Web.Data;
using Harbro.Web.Data.Constants;
using Harbro.Web.Data.Model;
using Harbro.Web.Data.Repository;
using Harbro.Web.ViewModel.Message;
using Harbro.Web.ViewModel.Order;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Harbro.Web.Controllers {

    [Authorize]
    public class OrderController : BaseController{

        private UserRepository userRepository;
        private ClientRepository clientRepository;
        private OrderRepository orderRepository;
        private ILogger<OrderController> logger;
        private readonly IMapper mapper;
        private DataContext context;
        private CustomerContext customerContext;

        public OrderController(UserRepository userRepository, ClientRepository clientRepository, OrderRepository orderRepository,
            ILogger<OrderController> logger, IMapper mapper, DataContext context, CustomerContext customerContext) {
            this.userRepository = userRepository;
            this.clientRepository = clientRepository;
            this.orderRepository = orderRepository;
            this.mapper = mapper;
            this.logger = logger;
            this.context = context;
            this.customerContext = customerContext;
        }

        public IActionResult Index() {
            return View();
        }

        public async Task<IActionResult> GetOrders([DataSourceRequest]DataSourceRequest request) {

            var result = new DataSourceResult();

            var serializer = new JsonSerializerSettings();

            var orders = await orderRepository.GetAll();

            result = orders.Select(p => mapper.Map<OrderModel>(p)).ToList().ToDataSourceResult(request);

            return Json(result, serializer);
            }

        public async Task<IActionResult> ViewOrder(Guid id, string message) {
            var model = await orderRepository.GetById(id);

            var client =  clientRepository.GetById(model.ClientId);

            model.Client = client;

            ViewBag.Message = message;

            return View(model);
        }


        public async Task<IActionResult> Edit(Guid id) {
            var model = await orderRepository.GetById(id);
            var client = clientRepository.GetById(model.ClientId);
            model.Client = client;
            

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Order model) {
          
           await orderRepository.Update(model);

            var message = string.Format("{0} has been successfully updated", model.ItemName);

            return RedirectToAction("ViewOrder", new { @id = model.OrderId , @message = message });
        }

        
        public async Task<IActionResult> Cancel(Guid id) {
            var model = await orderRepository.GetById(id);

            model.DateCancelled = DateTime.Now;
            model.Status = StatusConstant.Cancelled;

           await orderRepository.Update(model);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Deliver(Guid id) {
            var model = await orderRepository.GetById(id);

            model.DateDelivered = DateTime.Now;
            model.Status = StatusConstant.Delivered;

            await orderRepository.Update(model);

            var message = string.Format("{0} has been successfully marked as delivered", model.ItemName);

            return RedirectToAction("Index", "Home", new { @message = message });
            }

        public async Task<IActionResult> RepeatOrder(Guid id) {
            var model = await orderRepository.GetById(id);
            ViewBag.Id = id;
            return View(model);
            }

        [HttpPost]
        public async Task<IActionResult> Repeat(Order model, Guid id) {
            var order = await orderRepository.GetById(id);
            model = new Order {
                ClientId = order.ClientId,
                DeliveryAddress = model.DeliveryAddress,
                DateRequired = model.DateRequired,
                Quantity = model.Quantity,
                DeliveryMethod = model.DeliveryMethod,
                ItemId = model.ItemId,
                ItemName = model.ItemName,
                Status = model.Status,
                Units = model.Units,
                Notes = model.Notes,
            };

           await orderRepository.Create(model);

            return RedirectToAction("Index", "Home");
        }
    }
}

harbro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Manage Orders";
}
<style>
    #orderGrid .k-grid-header .k-header {
        background-color: #000 !important;
    }

    .k-header .k-icon {
        color: #808080 !important;
    }
    .k-grid tr td{
        cursor: pointer !important;
    }
</style>
<div style="margin-bottom: -11px;">
    <h1 style="color:#fff;text-align:center">Manage Orders</h1>

</div>
<br />
<br />
<div class="panel">
    <div class="panel-body">
        <div class="pull-right">
            <form class="form-horizontal pull-right" role="form" style="margin-right: 20px;margin-bottom:10px;margin-top:20px">
                <div class="form-group">
                    <div class="col-lg-12">
                        <input id="orderSearch" placeholder="Search Orders..." type="text" class="form-control" style="font-size: 14px; border-radius: 4px" />
                    </div>
                </div>
            </form>
        </div>
        <h2 style="font-weight:600; color:#DA291C">Order History</h2>
        <br />
        @(Html.Kendo().Grid<Harbro.Web.ViewModel.Order.OrderModel>()
          .Name("orderGrid")
          .Columns(c => {
              c.Bound(p => p.DateString).Title("Date");
              c.Bound(p => p.QuantityString).Title("Quantity").ClientTemplate("#=QuantityString#");
              c.Bound(p => p.Units).Title("Units (kg / tonnes)");
              c.Bound(p => p.ItemName).Title("Item Name");
              c.Bound(p => p.ItemId).Title("Item Id");
              c.Bound(p => p.ClientId).Title("Client").ClientTemplate("#=Client.Name#");
              c.Bound(p => p.ClientNumber).Title("Account Number").ClientTemplate("#=ClientNumber#");
              c.Bound(p => p.DeliveryMethod).Title("Delivery Method");
              c.Bound(p => p.StatusDescription).Title("Order Status").ClientTemplate("<span style='font-weight: 600;color:#=StatusTextColour#'>#=StatusDescription#</span><a href = '" + @Url.Action("ViewOrder", "Order", new { @id = "" }) + "/#=OrderId#' >");
          })
          .Sortable()
          .Filterable()
          .Groupable()
          .Pageable()
          .Selectable(selectable => selectable.Mode(GridSelectionMode.Single))
          .Events(e => e.Change("onSelect"))
          .Scrollable(s => s.Height("500px"))
          .Resizable(c => c.Columns(true))
          .ColumnMenu(c => c.Columns(true))
          .DataSource(dataSource => dataSource
          .Ajax()
          .Model(m => {
              m.Id(p => p.OrderId);
          })
          .PageSize(20)
          .Read(read => read.Action("GetOrders", "Order"))))
    </div>
</div>

@section Scripts{
    <script>
        var viewModel = new kendo.observable({
            baseCompanyLocationName: "",
            totalUsers: 0,
        });

        function onSelect() {
            var grid = $("#orderGrid").data("kendoGrid");
            var selectedItem = grid.dataItem(grid.select());
            var orderId = selectedItem.OrderId;
            window.location.href = "/Order/ViewOrder/" + orderId
        }

        function speciesChange() {
            var value = this.value(),
                orderGrid = $("#orderGrid").data("kendoGrid");

            if (value) {
                orderGrid.dataSource.filter({ field: "SpeciesDescription", operator: "contains", value: value });
            } else {
                orderGrid.dataSource.filter({});
            }
        }

        $("#orderSearch").keyup(function () {
            var query = $("#orderSearch").val();

            var orderGrid = $("#orderGrid").data("kendoGrid");

            if (query != null && query.length > 0) {
                var filter = {
                    logic: "or",
                    filters: [
                        { field: "ClientNumber", operator: "contains", value: query },
                        { field: "ItemName", operator: "contains", value: query },
                         { field: "ItemId", operator: "contains", value: query },
                        { field: "StatusDescription", operator: "contains", value: query },
                        { field: "Client.Name", operator: "contains", value: query },
                        { field: "QuantityString", operator: "contains", value: query },
                        { field: "DateString", operator: "contains", value: query }
                    ]
                };

                orderGrid.dataSource.filter(filter);
            } else {
                orderGrid.dataSource.filter([]);
            }
        });

        kendo.bind(document.body.children, viewModel);
    </script>
    @if (ViewBag.Message != null) {
        <script type="text/javascript">
            window.onload = function () {
                swal("", "@ViewBag.Message", "success")
            };
        </script>
        }
}